# Cloud builder for the dotnet builder.

steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'HelloWorld'
  env: [ 'DOTNETPATH=HelloWorld' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '/workspace/HelloWorld/bin/Release/netcoreapp2.1/publish/', '--stop-previous-version', '-v=10' ]
  env: [ 'DOTNETPATH=HelloWorld' ]

artifacts:
  objects:
    location: 'gs://stg-sviridov/dotnettest'
    paths: [ '/workspace/HelloWorld/bin/Release/netcoreapp2.1/publish/*' ]
